<?php

/**
 * ammo_menu
 * ammo_theme
 * ammo_overview_content
 * ammo_entity_info
 */

/**
 * Implements hook_init().
 */
function ammo_init() {
  module_load_include("inc", "ammo", "ammo");
}

function ammo_menu() {
  $items = array();

  $items['ammo'] = array(
    'title' => 'Amendementen en Moties',
    'page callback' => 'ammo_overview_content',
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'user_is_logged_in',
  );

  $items['ammo/ammo'] = array(
    'title' => 'Overzicht',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access callback' => 'user_is_logged_in',
    'weight' => 0,
  );

  $items['ammo/amendment'] = array(
    'title' => 'Amendementen',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ammo_amendment_form', 2, 3),
    'file' => 'amendment.form.inc',
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'ammo_add_access',
    'weight' => 1,
  );

  $items['ammo/motion'] = array(
    'title' => 'Moties',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ammo_motion_form', 2, 3),
    'file' => 'motion.form.inc',
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'ammo_add_access',
    'weight' => 2,
  );

  $items['ammo/meeting'] = array(
    'title' => 'Bijeenkomst',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ammo_meeting_form'),
    'file' => 'meeting.form.inc',
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'ammo_superadmin_access',
    'weight' => 3,
  );

  $items['ammo/document'] = array(
    'title' => 'Document',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ammo_document_form'),
    'file' => 'document.form.inc',
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'ammo_superadmin_access',
    'weight' => 4,
  );

  $items['ammo/autocomplete_members/%/%'] = array(
    'page callback' => 'ammo_autocomplete_members',
    'page arguments' => array(2, 3),
    'file' => 'ammo.inc',
    'type' => MENU_CALLBACK,
    'access callback' => 'user_is_logged_in',
  );

  return $items;
}

function ammo_permission() {
  return array(
    'administer ammo' => array(
      'title' => 'Beheer ammo',
    ),
    'administer amendments and motions' => array(
      'title' => 'Beheer amendementen en moties',
    ),
    'add amendments and motions' => array(
      'title' => 'Voeg amendementen en moties toe',
    ),
  );
}

function ammo_superadmin_access() {
  return user_access('administer ammo');
}

function ammo_admin_access() {
  return user_access('administer ammo') || user_access('administer amendments and motions');
}

function ammo_add_access() {
  return user_access('administer ammo') || user_access('administer amendments and motions') || user_access('add amendments and motions');
}

function ammo_theme() {
  $theme = array(
    'overview' => array(
      'template' => 'overview',
      'variables' => array(
        'test' => 'TEST',
      ),
    ),
    'amendment_form' => array(
      'render element' => 'form',
      'template' => 'amendment-form',
    ),
    'motion_form' => array(
      'render element' => 'form',
      'template' => 'motion-form',
    ),
    'meeting_form' => array(
      'render element' => 'form',
      'template' => 'meeting-form',
    ),
    'document_form' => array(
      'render element' => 'form',
      'template' => 'document-form',
    ),
    'amendment' => array(
      'variables' => array(),
      'template' => 'amendment',
    ),
    'motion' => array(
      'variables' => array(),
      'template' => 'motion',
    ),
  );
  return $theme;
}

function template_preprocess_amendment(&$variables) {
  if (isset($variables['entity_id'])) {
    $entity = entity_load_single('amendment', $variables['entity_id']);
    $document = entity_load_single('document', $entity->document_id);
    $meeting = entity_load_single('meeting', $document->meeting_id);
    $vars = array(
      'document_id' => $entity->document_id,
      'branch_id' => $entity->branch_id,
      'backed' => $entity->backed,
      'type' => $entity->type,
      'general' => $entity->general,
      'chapter' => $entity->chapter,
      'page' => $entity->page,
      'line' => $entity->line,
      'action' => $entity->action,
      'supplement' => $entity->supplement,
      'current_text' => $entity->current_text,
      'new_text' => $entity->new_text,
      'advice' => $entity->advice,
      'advice_general' => $entity->advice_general,
      'advice_supplement' => $entity->advice_supplement,
      'advice_action' => $entity->advice_action,
      'advice_current_text' => $entity->advice_current_text,
      'advice_new_text' => $entity->advice_new_text,
      'state' => $entity->state,
      'document_title' => $document->title,
      'document_description' => $document->description,
      'meeting_title' => $meeting->title,
      'meeting_description' => $meeting->description,
    );
    foreach($vars as $key => &$value) {
      $value = check_plain($value);
    }
    $variables = $variables + $vars;
  }
}

function template_preprocess_motion(&$variables) {
  if (isset($variables['entity_id'])) {
    $entity = entity_load_single('motion', $variables['entity_id']);
    $meeting = entity_load_single('meeting', $entity->meeting_id);
    $vars = array(
      'id' => $entity->id,
      'document_id' => $entity->document_id,
      'branch_id' => $entity->branch_id,
      'backed' => $entity->backed,
      'consideration_opening' => $entity->consideration_opening,
      'consideration_body' => $entity->consideration_body,
      'follow_up_opening' => $entity->follow_up_opening,
      'follow_up_body' => $entity->follow_up_body,
      'supplement' => $entity->supplement,
      'advice' => $entity->advice,
      'advice_consideration_opening' => $entity->advice_consideration_opening,
      'advice_consideration_body' => $entity->advice_consideration_body,
      'advice_follow_up_opening' => $entity->advice_follow_up_opening,
      'advice_follow_up_body' => $entity->advice_follow_up_body,
      'advice_supplement' => $entity->advice_supplement,
      'state' => $entity->state,
      'meeting_title' => $meeting->title,
      'meeting_description' => $meeting->description,
    );
    foreach($vars as $key => &$value) {
      $value = check_plain($value);
    }
    $variables = $variables + $vars;
  }
}

function ammo_overview_content() {
  return theme('overview', array());
}

  /**
   * Implements hook_entity_info().
   */
  function ammo_entity_info() {
    $info = array();

    $info['meeting'] = array(
      'label' => t('Meeting'),
      'entity class' => 'Entity',
      'controller class' => 'EntityAPIController',
      'base table' => 'ammo_meetings',
      'entity keys' => array(
        'id' => 'id',
      ),
    'fieldable' => FALSE,
  );
  
  $info['document'] = array(
    'label' => t('Document'),
    'entity class' => 'Entity',
    'controller class' => 'EntityAPIController',
    'base table' => 'ammo_documents',
    'entity keys' => array(
      'id' => 'id',
    ),
    'fieldable' => FALSE,
  );
  
  $info['amendment'] = array(
    'label' => t('Amendment'),
    'entity class' => 'Entity',
    'controller class' => 'EntityAPIController',
    'base table' => 'ammo_amendments',
    'entity keys' => array(
      'id' => 'id',
    ),
    'fieldable' => FALSE,
  );
  
  $info['motion'] = array(
    'label' => t('Motion'),
    'entity class' => 'Entity',
    'controller class' => 'EntityAPIController',
    'base table' => 'ammo_motions',
    'entity keys' => array(
      'id' => 'id',
    ),
    'fieldable' => FALSE,
  );

  $info['amendments_backers'] = array(
    'label' => t('Amendments backers relation'),
    'entity class' => 'Entity',
    'controller class' => 'EntityAPIController',
    'base table' => 'ammo_amendments_backers',
    'entity keys' => array(
      'id' => 'id',
    ),
    'fieldable' => FALSE,
  );

  $info['amendments_owners'] = array(
    'label' => t('Amendments owners relation'),
    'entity class' => 'Entity',
    'controller class' => 'EntityAPIController',
    'base table' => 'ammo_amendments_owners',
    'entity keys' => array(
      'id' => 'id',
    ),
    'fieldable' => FALSE,
  );

  $info['motions_backers'] = array(
    'label' => t('Motions backers relation'),
    'entity class' => 'Entity',
    'controller class' => 'EntityAPIController',
    'base table' => 'ammo_motions_backers',
    'entity keys' => array(
      'id' => 'id',
    ),
    'fieldable' => FALSE,
  );

  $info['motions_owners'] = array(
    'label' => t('Motions owners relation'),
    'entity class' => 'Entity',
    'controller class' => 'EntityAPIController',
    'base table' => 'ammo_motions_owners',
    'entity keys' => array(
      'id' => 'id',
    ),
    'fieldable' => FALSE,
  );

  return $info;
}
